// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQOn7lV2cignbCw4Uq6_RB_JaKjHLuqwg',
    appId: '1:120562347171:web:237cc2a3eda0aa1e222316',
    messagingSenderId: '120562347171',
    projectId: 'tealeafpro',
    authDomain: 'tealeafpro.firebaseapp.com',
    databaseURL: 'https://tealeafpro-default-rtdb.firebaseio.com',
    storageBucket: 'tealeafpro.firebasestorage.app',
    measurementId: 'G-SMJHM4RT3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hMrSmv-pjWNskK2nAH4ddPkfYFMMVJ0',
    appId: '1:120562347171:android:379936cf91d3e340222316',
    messagingSenderId: '120562347171',
    projectId: 'tealeafpro',
    databaseURL: 'https://tealeafpro-default-rtdb.firebaseio.com',
    storageBucket: 'tealeafpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_OefNOh4J2AhDrD3YaVE4m8imOdvaetA',
    appId: '1:120562347171:ios:d9d746e573879b00222316',
    messagingSenderId: '120562347171',
    projectId: 'tealeafpro',
    databaseURL: 'https://tealeafpro-default-rtdb.firebaseio.com',
    storageBucket: 'tealeafpro.firebasestorage.app',
    iosBundleId: 'com.example.iotTea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_OefNOh4J2AhDrD3YaVE4m8imOdvaetA',
    appId: '1:120562347171:ios:d9d746e573879b00222316',
    messagingSenderId: '120562347171',
    projectId: 'tealeafpro',
    databaseURL: 'https://tealeafpro-default-rtdb.firebaseio.com',
    storageBucket: 'tealeafpro.firebasestorage.app',
    iosBundleId: 'com.example.iotTea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQOn7lV2cignbCw4Uq6_RB_JaKjHLuqwg',
    appId: '1:120562347171:web:79374dbf476b336d222316',
    messagingSenderId: '120562347171',
    projectId: 'tealeafpro',
    authDomain: 'tealeafpro.firebaseapp.com',
    databaseURL: 'https://tealeafpro-default-rtdb.firebaseio.com',
    storageBucket: 'tealeafpro.firebasestorage.app',
    measurementId: 'G-CTJWZ29LXV',
  );
}
